# rbcrew/config/tasks.yaml

summarize_macroeconomics:
  description: >
    Summarize this report with a focus on macroeconomics and inflation:

    -------------
    REPORT TEXT

    {pdf_text}

    -------------

    Summarize the report in Swedish, focusing on macroeconomic and inflation-related aspects.
    Never include the original text in the summary. The analysis should not exceed 1000 words.

  expected_output: >
    Your output content is a summary of the report in Swedish, focusing on macroeconomic and inflation-related aspects.

    Format:

    - Title of the report that you are summarizing.
    - Date of publication of the report.
    - Summary of the report focusing on macroeconomic and inflation-related aspects.

    The summary should not exceed 1000 words. Never include the original text in the summary.

    Kom ihåg att aldrig inkludera originaltexten i sammanfattningen.
    Du ska skriva på svenska.

summary_export_impact:
  description: >
    Analyze this report with a focus on how Swedish companies with export operations may be affected:

    -------------
    REPORT
    -------------

    {pdf_text}

    -------------

    Analyze the report with a focus on how Swedish companies with export operations may be affected by the changes described in the report.
    Never include the original text in the summary. The analysis should not exceed 1000 words.

  expected_output: >
    Your output content is an analysis focusing on how Swedish companies with export operations may be affected by the changes described in the report.
    The analysis should not exceed 1000 words. Never include the original text in the summary.

    Kom ihåg att aldrig inkludera originaltexten i sammanfattningen.
    Du ska skriva på svenska.

compare_summaries_task:
  description: >

    Compare these summaries of reports and highlight changes between the reports.

    ------------
    SUMMARIES
    ------------

    {summaries}

    ------------

    Divide the analysis into two parts: an overall comparison and a more detailed analysis of how the conditions for Swedish export companies have changed.

  expected_output: >
    Your output content is a cohesive analysis in Swedish with two parts: an overall comparison of the two summaries and a more detailed analysis of how the conditions for Swedish export companies have changed.
    The analysis should not exceed 1000 words. Never include the original text in the summary.

    Kom ihåg att aldrig inkludera originaltexten i sammanfattningen.
    Du ska skriva på svenska.
